name: Tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: RSpec
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - rails: 'rails61'
            ruby: ['ruby-head', '3.0', '2.7', '2.6']
          - rails: 'rails60'
            ruby: ['ruby-head', '3.0', '2.7', '2.6']
          - rails: 'rails52'
            ruby: ['2.7', '2.6']
          - rails: 'rails51'
            ruby: ['2.7', '2.6']
          - rails: 'rails50'
            ruby: ['2.7', '2.6']

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup environment
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/administrate-prototype_test
        run: |
          bundle install
          bundle exec appraisal install
          cp .sample.env .env
          bundle exec rake db:setup
      - name: Run the tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/administrate-prototype_test
        run: |
          bundle exec appraisal ${{ matrix.rails }} rake
