name: Tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: RSpec
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rails:
          #- 'rails50'
          #- 'rails51'
          - 'rails52'
          #- 'rails60'
          - 'rails61'
        ruby:
          #- '2.5'
          #- '2.6'
          #- '2.7'
          - '3.0'

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup environment
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/example_app
        run: |
          bundle install
          bundle exec appraisal install
          cp .sample.env .env
          bundle exec rake db:setup
      - name: Run the tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/example_app
        run: |
          bundle exec appraisal ${{ matrix.rails }} rake
