name: Tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: RSpec
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rails:
          - 'rails50'
          - 'rails51'
          - 'rails52'
          - 'rails60'
          - 'rails61'
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup environment
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec appraisal ${{ matrix.rails }} bundle install
      - name: Run the tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        run: |
          bundle exec appraisal ${{ matrix.rails }} rake
